name: EisenInventories
main: eisenwave.inv.EisenInventoriesPlugin
version: 0.3
api-version: 1.13

permissions:
  eisen.inv:
    invtest:
      default: op
    cancelquery:
      default: true

commands:
  invtest:
    usage: "\u00A7cUsage: /invtest"
    permission: eisen.inv.invtest
  cancelquery:
    usage: "\u00A7cUsage: /cancelquery"
    permission: eisen.inv.cancelquery
